name: test

on: [push]

jobs:
    build:
        runs-on: ubuntu-latest
        if: "!contains(github.event.head_commit.message, 'initial commit')"

        strategy:
            matrix:
                python: ['3.8']

        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-python@v2
              with:
                  python-version: ${{ matrix.python }}

            - name: install dependencies
              run: |
                  pip install -U pip pytest yamllint

            - name: run yamllint
              run: |
                  yamllint .

            - name: run pytest
              run: |
                  pytest
